### ISSUE TITLE
关于预览和编辑框的三个建议……

### ISSUE THREAD

**Issue by AnnAngela** [Last-Order/Wikiplus#1]
1、能不能在预览时加一个返回编辑区的的链接，类似于Wiki自带的编辑器的那种……
![qq 20141208183531](https://cloud.githubusercontent.com/assets/9762652/5338025/80b9fd80-7f0a-11e4-97c3-6fbecb98445f.png)
2、能不能增加预览的快捷键，类似于Wiki自带的编辑器的那种（shift+alt+p）……
![qq 20141208183531](https://cloud.githubusercontent.com/assets/9762652/5338044/ae6355a6-7f0a-11e4-9e37-6b5142b5fd9b.png)
3、能不能自定义编辑框大小，类似于Wiki自带的编辑器的那种……
![qq 20141208183531](https://cloud.githubusercontent.com/assets/9762652/5338050/c7206fca-7f0a-11e4-8696-480fb5cccbed.png)

**Comment by Last-Order** [comment]
1 已实现..

**Comment by Last-Order** [comment]
2 想不出快捷键了
3 太麻烦了以后我闲的蛋疼再搞
