### ISSUE TITLE
编辑错误时没有重试按钮，而且编辑区域也不可用。

### ISSUE THREAD

**Issue by zyzsdy** [Last-Order/Wikiplus#13]
![qq 20150808104327](https://cloud.githubusercontent.com/assets/5925733/9148720/55301950-3dba-11e5-8c71-18e4b2748ab7.png)

编辑时碰到网络错误等原因编辑失败之后，编辑区域没有恢复为可用状态。同时无法再次提交。

这在使用Wikiplus做较大编辑的时候可能因为失败而丢失数据。

**Comment by Last-Order** [comment]
fixed.
