### ISSUE TITLE
编辑框挡住了上面的内容

### ISSUE THREAD

**Issue by zyzsdy** [Last-Order/Wikiplus#14]
Wikiplus的编辑框是固定的，在编辑时候会挡住上方的一部分内容。当我需要被挡住的内容做参考的时候就会很不方便。希望允许用户可以拖动编辑框。

**Comment by CFSO6459** [comment]
+1

**Comment by Last-Order** [comment]
solved by c5f4d5783bf6bb331bb8926452520a8bc63fe77e
