### ISSUE TITLE
编辑框触发时会滚动回顶部，体验不好。

### ISSUE THREAD

**Issue by zyzsdy** [Last-Order/Wikiplus#15]
在一个很长的页面中点击“快速编辑”。编辑框仍然触发在页面顶部，并使用js将页面自动滚动到顶部。这样的体验很不好。

建议允许编辑框在页面中任何地方弹出。最好弹出在页面浮动层上，使用position:absolute使得编辑框脱离页面流。

**Comment by Last-Order** [comment]
fixed.
