### ISSUE TITLE
功能请求：编辑失败时不disable编辑的textarea

### ISSUE THREAD

**Issue by ryRubyy** [Last-Order/Wikiplus#17]
当使用Wikiplus在不是特别稳定的Wiki/网络上编辑时，会出现编辑失败的情况。希望编辑失败时能够不禁用textarea，从而使编者能够复制修改内容再次/在MediaWiki的编辑器中进行提交。Thx.

**Comment by Last-Order** [comment]
1.9版本修正，但该版本还没有推送到非测试版，请稍等。稍后做处理。
