### ISSUE TITLE
Wikiplus速编框中是否需要显示编辑提示？

### ISSUE THREAD

**Issue by ryRubyy** [Last-Order/Wikiplus#18]
基于编辑方面，个人觉得需要。
基于快速编辑方面，个人觉得使用速编的话一般都用普通方式编辑过此页面，也就阅读过编辑提示。而且基于快速的方面也不需要显示。
也许写到配置里，让用户自己决定会更好？
Thx.

**Comment by Last-Order** [comment]
要显示编辑提示，就得多一次请求，这已经违背了本项目的本意。在可预见的未来不会加入该功能，见谅。

ryRubyy <notifications@github.com>于2015年8月14日周五 12:32写道：
