### ISSUE TITLE
未知的编辑错误

### ISSUE THREAD

**Issue by CFSO6459** [Last-Order/Wikiplus#19]
偶尔会出现“未知的编辑错误”，但是刷新页面后发现编辑已保存。求解决……

**Comment by Last-Order** [comment]
请提供更详细的信息，例如修订版本号。

**Comment by CFSO6459** [comment]
最新版本（版本号是多少来着…？）

附Q群中的讨论记录：
------------------------------------------------------------------------
2015-08-25
【rin】Minato Tomoka Metro (UTC+8)(503806558) 21:15:43
我这边编辑有个问题
【rin】Minato Tomoka Metro (UTC+8)(503806558) 21:16:41
我这边换了联想手机之后，每次在编辑完点保存，都会报“出错，编辑未保存”
【rin】Minato Tomoka Metro (UTC+8)(503806558) 21:16:49
但是实际上已经保存了，
【rin】Minato Tomoka Metro (UTC+8)(503806558) 21:17:10
只要我再打开一次条目就可以看到新的编辑版本
【umi】兔兔耳宝宝 +8(1367924387) 21:18:35
我也是有时会出现“未知的编辑错误”，但是在确认一次就会和自己冲突了
------------------------------------------------------------------------

**Comment by Last-Order** [comment]
我指的是mediawiki的修订版本号(revision)

---- CFSO6459编写 ----

**Comment by CFSO6459** [comment]
萌娘百科用的MW，是1.25？

**Comment by Last-Order** [comment]
不不不，我指的是提示未知错误的那次提交的历史版本号。

---- CFSO6459编写 ----

**Comment by CFSO6459** [comment]
453374、453748、454156
这些是记得的（能找到的）条目历史版本号

**Comment by Last-Order** [comment]
感谢，我会排查。

---- CFSO6459编写 ----

**Comment by Last-Order** [comment]
无法定位错误。由于我没有联想手机，无法做更真实的模拟。

**Comment by CFSO6459** [comment]
问题是我用台式机也出现了这个问题

**Comment by Last-Order** [comment]
新的版本加了未知错误的详细输出 如果有再遇到请提供一些具体的错误信息。

**Comment by CFSO6459** [comment]
新报告：
internal api error exception

**Comment by Last-Order** [comment]
唔。这个看起来不是wikiplus的锅。

**Comment by CFSO6459** [comment]
出现internal api error exception的时候，编辑实际已保存，能否让wikiplus“装作”编辑成功？

**Comment by Last-Order** [comment]
内部错误也分很多，这个难以判定。

---- CFSO6459编写 ----
