### ISSUE TITLE
section的「快速編輯」是個擺設嗎？

### ISSUE THREAD

**Issue by LNDDYL** [Last-Order/Wikiplus#22]
![_2015-11-04t10-33-00 298z](https://cloud.githubusercontent.com/assets/4318463/10935695/b30b6158-8322-11e5-80a6-b25ea94a382c.png)
點它沒有任何反應。

**Comment by Last-Order** [comment]
诶？我看看

LNDDYL <notifications@github.com>于2015年11月4日周三 18:35写道：

**Comment by Last-Order** [comment]
抱歉，无法复现。是否能提供更详细的信息，如页面名等？

**Comment by LNDDYL** [comment]
在任何頁面都一樣，火狐瀏覽器。

**Comment by Last-Order** [comment]
@LNDDYL 看上去是跟VE的冲突，已经在几个小时前解决。请刷新一下页面。如还有问题请重开Issue

**Comment by LNDDYL** [comment]
@Last-Order 目前又出現了新bug，點它與點全文快速編輯的效果是一樣的。

**Comment by Last-Order** [comment]
@LNDDYL bug提交请提供触发地点，如何触发，另外请另外开issue，谢谢。
