### ISSUE TITLE
快速编辑不支持导言部分的编辑

### ISSUE THREAD

**Issue by Last-Order** [Last-Order/Wikiplus#23]
rt

**Comment by zyzsdy** [comment]
现有的API可以支持导言部分的编辑么？

实际上，这个编辑按钮放在哪里也是个问题。

我一般是直接点全页的快速编辑按钮来编辑这个导言的。

**Comment by Last-Order** [comment]
有些wiki会在导言部分加一个编辑按钮……API还没研究过，不清楚。

zyzsdy <notifications@github.com>于2015年11月10日周二 22:02写道：

**Comment by Last-Order** [comment]
fix by 1e13830421c0230adb83cf47de41f2c6196635bb
