### ISSUE TITLE
数据统计应该鉴别一下提交数据

### ISSUE THREAD

**Issue by Last-Order** [Last-Order/Wikiplus#24]
太离谱的就拒绝掉。。

**Comment by zyzsdy** [comment]
所以应该制定一套什么过滤规则比较好？

比如负数全部过滤掉。。。。。。

另外我们需要进行一个客户端验证么？

**Comment by Last-Order** [comment]
简单过滤下就好吧……太离谱的扔掉就好，比如负数。其他验证就算了，感觉真要捣乱也拦不住。

zyzsdy <notifications@github.com>于2015年11月10日周二 22:00写道：

**Comment by zyzsdy** [comment]
还有个问题，需要记录扔掉的数据么？还是单纯的扔掉。

**Comment by Last-Order** [comment]
扔掉就好了。。嗯

zyzsdy <notifications@github.com>于2015年11月11日周三 09:32写道：

**Comment by zyzsdy** [comment]
Solved by commit c476ba5
