### ISSUE TITLE
更换域名的公告好烦啊！

### ISSUE THREAD

**Issue by CFSO6459** [Last-Order/Wikiplus#25]
每开一个新窗口都会弹一次，无论点“自动修改”还是关闭窗口的“x”，新页面都还是会继续弹窗。能否只弹一次，或加个“ √ 不再弹出本窗口”

**Comment by Last-Order** [comment]
这是一次强制升级。我必须让所有人看到……再说改了不就没有了吗

CFSO6459 <notifications@github.com>于2015年11月14日周六 01:02写道：

**Comment by CFSO6459** [comment]
然而现在的测试结果还是：点“自动修改”之后，刷新页面或开新页面，仍然会弹窗。清理浏览器缓存、更换浏览器（360chrome、Google Chrome）都还处在问题

**Comment by Last-Order** [comment]
那个是针对common.js加载的自动修改。你那是缓存锅。请尝试在参数设置-小工具里停用再启用。

**Comment by CFSO6459** [comment]
停用再启用并没有改善……

**Comment by zyzsdy** [comment]
mw的锅，mw的小工具设置会对每个人单独缓存，且缓存在mw内部。
建议对小工具设置进行有效修改后保存，然后清除浏览器缓存，可能有所改善。

common.js加载肯定没有问题。
萌百因为直接安装到小工具列表里，本来想的是只要修改掉就好了，结果还有缓存锅。。。

**Comment by Last-Order** [comment]
结论：Mediawiki坑爹
