### ISSUE TITLE
数据统计在11.14之后未能采集到数据

### ISSUE THREAD

**Issue by Last-Order** [Last-Order/Wikiplus#27]
RT

**Comment by zyzsdy** [comment]
![image](https://cloud.githubusercontent.com/assets/5925733/11197758/91e95692-8cfa-11e5-8c88-6fe0cf23fcdc.png)

如图，404了。。。

**Comment by zyzsdy** [comment]
解决方案，请将URL中的statistic替换为statistics。

真不知道拼写错误为啥还要开issue

**Comment by Last-Order** [comment]
因为我没法调试并不知道错在哪啊……

**Comment by zyzsdy** [comment]
我用的这个iOS上的黑科技调试器：Surge
应用商店里卖10美元。

Android还真没这么好用的工具。

**Comment by zyzsdy** [comment]
Resolved by 6767633
