### ISSUE TITLE
WikiPlus在某些页面崩掉

### ISSUE THREAD

**Issue by AnnAngela** [Last-Order/Wikiplus#3]
已知在http://zh.moegirl.org/Template:%E7%BB%8F%E5%85%B8%E4%BA%BA%E7%89%A9%E5%88%97%E8%A1%A8%E6%8F%90%E9%86%92 上无法使用快速编辑功能
![img_20150104_171422](https://cloud.githubusercontent.com/assets/9762652/5605470/290e6538-9438-11e4-8166-aba9cda72474.jpg)

**Comment by Last-Order** [comment]
好我关注一下。。

**Comment by Last-Order** [comment]
有点麻烦..我得想想

**Comment by Last-Order** [comment]
暂时无解
