### ISSUE TITLE
应增加对历史版本编辑的判断

### ISSUE THREAD

**Issue by Last-Order** [Last-Order/Wikiplus#30]

**Comment by Last-Order** [comment]
Mediawiki在浏览历史版本时。
wgCurRevisionId与wgRevisionId不等。
wgRevisionId可以作为页面的唯一标识。

**Comment by Jasonzhuocn** [comment]
我的確多次遇到這個狀況。
我時常進歷史版本動手修改。快速編輯點下去跳出來的文字不同，才想起自己是在歷史版本中。

**Comment by Last-Order** [comment]
@Jasonzhuocn 我会尽快解决

**Comment by Last-Order** [comment]
solved by dc6aee24275bfe7f306518e8b682d7f664d1f8ca
