### ISSUE TITLE
当参数设置中的“自动将标题编号”被选中时，Wikiplus无法正确取得段落标题

### ISSUE THREAD

**Issue by liangent** [Last-Order/Wikiplus#34]
自动生成的编号会被作为段落标题的一部分，放入 /* section title */ 注释

**Comment by Last-Order** [comment]
了解并复现，感谢回报。

**Comment by Last-Order** [comment]
solved by 28ffdb9d0e4410ea07857db82d0a0737abf2a755

**Comment by cpplearner** [comment]
看起来这个 fix 引入了新的问题
现在的问题是：只要段落标题包含链接，就无法正确取得段落标题
比如说，如果段落标题（wikicode源码）是
```
== [[Google_Talk娘]]图片似乎是冒用作品 ==
```

那么获得的标题是`图片似乎是冒用作品`

**Comment by Last-Order** [comment]
……喔……瞬间明白了，太激进了直接扔掉了所有标签……知道了。

S. B. Tam <notifications@github.com>于2016年2月18日周四 18:13写道：
