### ISSUE TITLE
releaseNote应该支持多语言

### ISSUE THREAD

**Issue by zyzsdy** [Last-Order/Wikiplus#37]
现在的releaseNote无法支持多语言，在英文版上表现不好。

安装更新后仍然显示中文版更新内容。

**Comment by LNDDYL** [comment]
作者並沒有把它進行多語系處理。

**Comment by LNDDYL** [comment]
https://github.com/Last-Order/Wikiplus/blob/master/Main.new.js
這裡根本沒有進行多語系處理！

**Comment by Last-Order** [comment]
@LNDDYL 我知道，别激动。

**Comment by zyzsdy** [comment]
Minor bug fixes
嗯。。
