### ISSUE TITLE
语言文件版本号不应绑定主程序版本号

### ISSUE THREAD

**Issue by zyzsdy** [Last-Order/Wikiplus#38]
语言文件不一定跟着主程序更新，所以我觉得应该将语言文件的版本号与主程序版本号区分开来。

通过记录各语言文件的版本号来保持更新，而不是现在这样，即使语言文件一字未动，只是主程序修个 bug，也要改版本号。

**Comment by Last-Order** [comment]
solved by 34fdc842dc08ac3d4d4413a81fbffc6382814c66
