### ISSUE TITLE
在没有“到编辑框”按钮时出现问题

### ISSUE THREAD

**Issue by AnnAngela** [Last-Order/Wikiplus#4]
不要说话，用心去体会……

![20150105125722](https://cloud.githubusercontent.com/assets/9762652/5609530/68449d9e-94dd-11e4-96e4-cf0148ef6b49.png)

**Comment by Last-Order** [comment]
你这么一说我就想起来了。。

**Comment by Last-Order** [comment]
3645a1dcc402deb52d2fd6cabac54e3e66dc2bcb 解决问题。
