### ISSUE TITLE
代码冲突bug？

### ISSUE THREAD

**Issue by CFSO6459** [Last-Order/Wikiplus#9]
快速编辑时，不点预览也会出现下面的文字内容（如图）：

![1](https://cloud.githubusercontent.com/assets/10977601/7952432/1de83808-0983-11e5-9d1e-e3f6238797ad.png)

发生问题的页面是 [[Talk:讨论版#分段一：有关于条目名是否应当出现标点符号的讨论]]

**Comment by Last-Order** [comment]
收到。周末确认。

---- CFSO6459编写 ----

**Comment by Last-Order** [comment]
目测某模板内容错误封闭主内容标签……正在定位。

**Comment by Last-Order** [comment]
1.7.2版本修复w
